// Auth types
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// Seeds types
export const GET_SEEDS_REQUEST = 'GET_SEEDS_REQUEST'
export const GET_SEEDS_SUCCESS = 'GET_SEEDS_SUCCESS'
export const GET_SEEDS_ERROR = 'GET_SEEDS_ERROR'
export const ADD_SEED_REQUEST = 'ADD_SEED_REQUEST'
export const ADD_SEED_SUCCESS = 'ADD_SEED_SUCCESS'
export const ADD_SEED_ERROR = 'ADD_SEED_ERROR'
export const ADD_SEED_BANK_REQUEST = 'ADD_SEED_BANK_REQUEST'
export const ADD_SEED_BANK_SUCCESS = 'ADD_SEED_BANK_SUCCESS'
export const ADD_SEED_BANK_ERROR = 'ADD_SEED_BANK_ERROR'
export const GET_SEED_BANKS_REQUEST = 'GET_SEED_BANKS_REQUEST'
export const GET_SEED_BANKS_SUCCESS = 'GET_SEED_BANKS_SUCCESS'
export const GET_SEED_BANKS_ERROR = 'GET_SEED_BANKS_ERROR'
export const UPDATE_SEED = 'UPDATE_SEED'
export const DELETE_SEED = 'DELETE_SEED'

// Batch types
export const FETCH_BATCHES_REQUEST = 'FETCH_BATCHES_REQUEST'
export const FETCH_BATCHES_SUCCESS = 'FETCH_BATCHES_SUCCESS'
export const FETCH_BATCHES_ERROR = 'FETCH_BATCHES_ERROR'
export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST'
export const ADD_BATCH_SUCCESS = 'ADD_BATCH_SUCCESS'
export const ADD_BATCH_ERROR = 'ADD_BATCH_ERROR'
export const UPDATE_BATCH_REQUEST = 'UPDATE_BATCH_REQUEST'
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS'
export const UPDATE_BATCH_ERROR = 'UPDATE_BATCH_ERROR'
export const DELETE_BATCH_REQUEST = 'DELETE_BATCH_REQUEST'
export const DELETE_BATCH_SUCCESS = 'DELETE_BATCH_SUCCESS'
export const DELETE_BATCH_ERROR = 'DELETE_BATCH_ERROR'

// Batch Log types
export const ADD_BATCH_LOG_REQUEST = 'ADD_BATCH_LOG_REQUEST'
export const ADD_BATCH_LOG_SUCCESS = 'ADD_BATCH_LOG_SUCCESS'
export const ADD_BATCH_LOG_ERROR = 'ADD_BATCH_LOG_ERROR'
export const UPDATE_BATCH_LOG_REQUEST = 'UPDATE_BATCH_LOG_REQUEST'
export const UPDATE_BATCH_LOG_SUCCESS = 'UPDATE_BATCH_LOG_SUCCESS'
export const UPDATE_BATCH_LOG_ERROR = 'UPDATE_BATCH_LOG_ERROR'
export const DELETE_BATCH_LOG_REQUEST = 'DELETE_BATCH_LOG_REQUEST'
export const DELETE_BATCH_LOG_SUCCESS = 'DELETE_BATCH_LOG_SUCCESS'
export const DELETE_BATCH_LOG_ERROR = 'DELETE_BATCH_LOG_ERROR'
export const FETCH_BATCH_LOGS_REQUEST = 'FETCH_BATCH_LOGS_REQUEST'
export const FETCH_BATCH_LOGS_SUCCESS = 'FETCH_BATCH_LOGS_SUCCESS'
export const FETCH_BATCH_LOGS_ERROR = 'FETCH_BATCH_LOGS_ERROR'

// Patient types
export const FETCH_PATIENTS = 'FETCH_PATIENTS'
export const ADD_ORDER = 'ADD_ORDER'

// Common
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'

// Organization types
export const REGISTER_ORGANIZATION_REQUEST = 'REGISTER_ORGANIZATION_REQUEST'
export const REGISTER_ORGANIZATION_SUCCESS = 'REGISTER_ORGANIZATION_SUCCESS'
export const REGISTER_ORGANIZATION_FAILURE = 'REGISTER_ORGANIZATION_FAILURE'

// User types
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'
