// Auth types
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

// Product types
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// Batch types
export const FETCH_BATCHES = 'FETCH_BATCHES'
export const ADD_BATCH = 'ADD_BATCH'
export const UPDATE_BATCH = 'UPDATE_BATCH'

// Patient types
export const FETCH_PATIENTS = 'FETCH_PATIENTS'
export const ADD_ORDER = 'ADD_ORDER'

// Common
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
